blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.CharField(max_length=255, unique=True, **NULLABLE, verbose_name='Slug')
    body = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='posts/', **NULLABLE, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано?')
    view_count = models.IntegerField(default=0, verbose_name='Счетчик просмотров')

    author = models.ForeignKey(User, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Автор')

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

blog/forms.py
from django import forms

from blog.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title", "body", "image")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control'})

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse

# Create your views here.
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify

from blog.forms import PostForm
from blog.models import Post


class PostListView(LoginRequiredMixin, ListView):
    model = Post

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    context_object_name = 'post'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:post_list')

    def form_valid(self, form):
        if form.is_valid():
            post = form.save(commit=False)
            post.slug = slugify(post.title)
            user = self.request.user
            post.author = user
            post.save()
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.slug = slugify(new_post.title)
            new_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:post_detail', args=[self.kwargs['pk']])

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user == self.get_object().author


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user == self.get_object().author

blog/templates/blog/post_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Удаление поста</h2>
            <p>Вы уверены, что хотите удалить пост "{{ post.title }}"?</p>
            <form method="post" action="{% url 'blog:post_delete' post.pk %}">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Удалить">
            </form>
            <div class="mt-2">
                <a href="{% url 'blog:post_list' %}" class="btn btn-secondary">Отмена</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'catalog/base.html' %}
{% load blog_tags %}

{% block content %}

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-4 d-flex align-items-center justify-content-center mb-4">
                <img src="{{ post.image | media_path }}" class="img-fluid rounded-start" style="height: 300px;"
                     alt="Post Image">
            </div>
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-8">
                <div class="text-center">
                    <h2 class="mt-4">{{ object.title }}</h2>
                    <p>{{ object.slug }}</p>
                    <p>{{ object.body }}</p>
                    <p><small class="text-muted">{{ object.created_at }}</small></p>
                    <p>Просмотры: {{ object.view_count }}</p>
                    {% if user == object.author or user.is_superuser %}
                        <div class="col-md-4 mx-auto mb-4">
                            <a href="{% url 'blog:post_update' object.pk %}" class="btn btn-warning btn-lg btn-block">Изменить</a>
                        </div>
                        <div class="col-md-4 mx-auto mb-4">
                            <a href="{% url 'blog:post_delete' object.pk %}" class="btn btn-danger btn-lg btn-block">Удалить</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'catalog/base.html' %}
{% load blog_tags %}

{% block content %}
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
        {% if user.is_authenticated %}
            <div class="col-md-4 d-flex align-items-center justify-content-center mb-4">
                <a href="{% url 'blog:post_create' %}" class="btn btn-primary btn-lg btn-block">Опубликовать
                    новый отзыв</a>
            </div>
        {% endif %}
            {% for post in object_list %}
                <div class="card mb-4" style="max-width: 100%;">
                    <div class="row g-0">
                        <div class="col-md-4 d-flex align-items-center justify-content-center">
                            <img src="{{ post.image | media_path }}" class="img-fluid rounded-start" style="height: 300px;"
                                 alt="Post Image">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body mt-2 mb-2">
                                <h2 class="my-0 mr-md-auto font-weight-bold">{{ post.title }}</h2>
                                <br>
                                <p class="card-text">{{ post.body | truncatechars:100 }}</p>
                                <p class="card-text">{{ post.created_at }}</p>
                                <a href="{% url 'blog:post_detail' post.pk %}"
                                   class="btn btn-primary btn-lg btn-block">Прочитать полностью</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}