blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users import views

app_name = UsersConfig.name

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('confirm_register/<str:token>/', views.RegisterConfirmView.as_view(), name='confirm_register'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

NULLABLE = {'blank': True, 'null': True}

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Почта')

    phone_number = models.CharField(max_length=20, unique=True, **NULLABLE, verbose_name='Номер телефона')
    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='Фото профиля')
    country = models.CharField(max_length=50, **NULLABLE, verbose_name='Страна')

    token = models.CharField(max_length=100, **NULLABLE, verbose_name='Токен')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordResetForm, SetPasswordForm, \
    AuthenticationForm

from catalog.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone_number', 'country', 'avatar')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserPasswordResetForm(StyleFormMixin, PasswordResetForm):
    class Meta:
        model = User


class UserPasswordSetForm(StyleFormMixin, SetPasswordForm):
    class Meta:
        model = User


class UserAuthenticationForm(StyleFormMixin, AuthenticationForm):
    class Meta:
        model = User

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView, LoginView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView
from django.core.mail import send_mail

from config import settings
from users.forms import UserRegisterForm, UserProfileForm, UserPasswordResetForm, UserPasswordSetForm, UserAuthenticationForm
from users.models import User


# Create your views here.

class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserAuthenticationForm


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False

        token = secrets.token_hex(16)
        user.token = token
        user.save()

        host = self.request.get_host()
        url = f'http://{host}/users/confirm_register/{token}'

        send_mail(
            subject='Подтверждение регистрации',
            message=f'Здравствуйте, перейдите по ссылке для подтверждения почты {url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email]
        )

        return super().form_valid(form)


class RegisterConfirmView(TemplateView):
    template_name = 'users/confirm_register.html'
    def post(self, request, *args, **kwargs):
        token = kwargs.get('token')
        user = get_object_or_404(User, token=token)
        user.is_active = True
        user.save()
        return redirect(reverse('users:login'))


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    form_class = UserPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'users/password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    form_class = UserPasswordSetForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'

users/templates/users/confirm_register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-4 d-flex align-items-center justify-content-center mb-4">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-lg btn-block btn-success">
                    Подтвердить
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                {{ form.as_p }}
                <a class="text-muted" href="{% url 'users:password_reset' %}">Забыли пароль?</a>
                <br>
                <button type="submit" class="btn btn-lg btn-block btn-success">
                    Войти
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h3> Сброс пароля </h3>
                <form method="post" action="{% url 'users:password_reset_done' %}" class="mb-4">
                    {% csrf_token %}
                    {{ form.email.label_tag }} {{ form.email }}
                    <br>
                    <div class="col-md-4 mx-auto mb-4">
                        <button type="submit" class="btn btn-success btn-lg btn-block">Отправить запрос</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <p>Ваш пароль был успешно изменен.</p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h3> Сброс пароля </h3>
                <form method="post">
                    {% csrf_token %}
                    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
                    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
                    <br>
                    <button type="submit" class="btn btn-success btn-lg btn-block">Сбросить пароль</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <p>На ваш адрес электронной почты было отправлено письмо с инструкциями по сбросу пароля.</p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
    {% blocktranslate %}You're receiving this email because you requested a password reset for your user account at
        {{ site_name }}.{% endblocktranslate %}

    {% translate "Please go to the following page and choose a new password:" %}
    {% block reset_link %}
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    {% endblock %}

    {% translate "Thanks for using our site!" %}

    {% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h3> Сброс пароля </h3>
                <form method="post" action="{% url 'users:password_reset' %}" class="mb-4">
                    {% csrf_token %}
                    {{ form.email.label_tag }} {{ form.email }}
                    <br>
                    <div class="col-md-4 mx-auto mb-4">
                        <button type="submit" class="btn btn-success btn-lg btn-block">
                            Отправить запрос
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-lg btn-block btn-success">
                    Зарегистрироваться
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-lg btn-block btn-success">
                    Сохранить
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}