blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog import views
from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', views.CategoryListView.as_view(), name='home'),
    path('contacts/', cache_page(60)(views.contacts), name='contacts'),
    path('categories/<int:pk>/', views.ProductListView.as_view(), name='product_list'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/create/', views.ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('products/<int:pk>/versions/', views.VersionDetailView.as_view(), name='version_detail'),
    path('versions/create/', views.VersionCreateView.as_view(), name='version_create'),
    path('versions/<int:pk>/update/', views.VersionUpdateView.as_view(), name='version_update'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models

from users.models import User

# Create your models here.

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    photo = models.ImageField(upload_to='products/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')

    is_published = models.BooleanField(default=True, verbose_name='Опубликовано?')

    owner = models.ForeignKey(User, **NULLABLE, on_delete=models.SET_NULL, verbose_name='Продавец')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        permissions = [
            ('can_edit_description', 'Can edit description'),
            ('can_edit_category', 'Can edit category'),
            ('can_cancel_publishing', 'Can cancel publishing'),
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.IntegerField(default=1, verbose_name='Номер версии')
    version_title = models.CharField(max_length=255, verbose_name='Название версии')
    is_actual = models.BooleanField(default=True, verbose_name='Версия актуальна?')

    def __str__(self):
        return f'{self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.models import Product, Version


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, forms.BooleanField):
                field.widget.attrs.update({'class': 'form-check_input'})
            else:
                field.widget.attrs.update({'class': 'form-control'})


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("created_at", "updated_at", "owner", "is_published")

    def clean_name(self):
        name = self.cleaned_data.get("name")
        forbidden_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно",
                           "мошенничество", "полиция", "радар"]

        for word in forbidden_words:
            if word.lower() in name.lower():
                raise ValidationError(f"Слово '{word}' запрещено использовать в названии продукта. ")

        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        forbidden_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно",
                           "мошенничество", "полиция", "радар"]

        for word in forbidden_words:
            if word.lower() in description.lower():
                raise ValidationError(f"Слово '{word}' запрещено использовать в описании продукта.")

        return description


class ProductModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ("description", "category", "is_published")

    def clean_name(self):
        name = self.cleaned_data.get("name")
        forbidden_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно",
                           "мошенничество", "полиция", "радар"]

        for word in forbidden_words:
            if word.lower() in name.lower():
                raise ValidationError(f"Слово '{word}' запрещено использовать в названии продукта. ")

        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        forbidden_words = ["казино", "криптовалюта", "крипта", "биржа", "дешево", "бесплатно",
                           "мошенничество", "полиция", "радар"]

        for word in forbidden_words:
            if word.lower() in description.lower():
                raise ValidationError(f"Слово '{word}' запрещено использовать в описании продукта.")

        return description


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        exclude = ("is_actual", "version_number")

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Category, Version

from catalog.services import get_cached_category_list, get_cached_product_info


class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = get_cached_category_list()
        return context


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Product.objects.filter(category_id=self.kwargs['pk'])
        return context


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_info = get_cached_product_info(kwargs['object'].pk)
        context['product_name'] = product_info['name']
        context['product_category'] = product_info['category']
        context['product_created_at'] = product_info['created_at']
        return context


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.add_product'
    success_url = reverse_lazy('catalog:home')

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        ProductFormset = inlineformset_factory(Product, Version, form=ProductForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = ProductFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ProductFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save(commit=False)

        if formset.is_valid():
            formset.instance = self.object
            formset.instance.updated_at = timezone.now()
            formset.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('catalog:product_detail', args=[self.kwargs['pk']])

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm

        if user.groups.filter(name="Moderator").exists():
            return ProductModeratorForm

        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:home')
    permission_required = 'catalog.delete_product'
    context_object_name = 'product'

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user == self.get_object().owner or user.groups.filter(name="Moderator").exists()


class VersionDetailView(LoginRequiredMixin, DetailView):
    model = Version

    def get_object(self, queryset=None):
        version = Version.objects.get(product=self.kwargs['pk'], is_actual=True)
        return version


class VersionCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Version
    form_class = VersionForm
    permission_required = 'catalog.add_version'
    success_url = reverse_lazy('catalog:home')


class VersionUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Version
    form_class = VersionForm
    permission_required = 'catalog.change_version'
    success_url = reverse_lazy('catalog:home')

    def get_object(self, queryset=None):
        version = Version.objects.get(product=self.kwargs['pk'], is_actual=True)
        version.is_actual = False
        version.save()

        self.object = super().get_object(queryset)
        self.object.is_actual = True
        self.object.save()
        return self.object


@login_required
def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'name: {name}\nphone: {phone}\nmessage: {message}')
    return render(request, 'catalog/contacts.html')

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VadimStore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
</head>
<body>

{% include 'catalog/includes/top.html' %}

<div class="container">
    {% block content %}
    {% endblock %}

    {% include 'catalog/includes/bottom.html' %}
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Российская Федерация</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>228-991-420-69</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>г. Дивный, ул. Пушкина, д. Калатушкина</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Напишите ваш отзыв" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row justify-content-center">
    {% if user.is_authenticated %}
        <div class="col-md-4 d-flex align-items-center justify-content-center mb-4">
            <a href="{% url 'catalog:product_create' %}" class="btn btn-primary btn-lg btn-block">Добавить
                новый товар</a>
        </div>
    {% endif %}
    </div>
    <div class="row text-center">
        {% for ctg in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ ctg }}</h4>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            {% if ctg.description %}
                                {{ ctg.description | truncatechars:60 }}
                            {% else %}
                                Описание отсутствует.
                                Ждем, пока владелец его добавит.
                            {% endif %}
                        </ul>
                        <a href="{% url 'catalog:product_list' ctg.pk %}" type="button"
                           class="btn btn-lg btn-block btn-outline-primary">Перейти к товарам</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Удаление товара</h2>
            <p>Вы уверены, что хотите удалить товар "{{ product.name }}"?</p>
            <form method="post" action="{% url 'catalog:product_delete' product.pk %}">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Удалить">
            </form>
            <div class="mt-2">
                <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-secondary">Отмена</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ product.photo | media_path }}" alt="Product Image" class="img-fluid">
            </div>
            <div class="col-md-6">
                <h2 class="display-4">{{ product_name }}</h2>
                <p class="lead">Цена: {{ product.price }}₽</p>
                <p class="lead">
                    {% if product.description %}
                        {{ product.description }}
                    {% else %}
                        Описание отсутствует.
                        Ждем, пока продавец его добавит.
                    {% endif %}
                </p>
                <p class="lead">Категория: {{ product_category }}</p>
                <p class="lead">Дата добавления: {{ product_created_at }} </p>

                <div class="mt-2">
                    <a href="{% url 'catalog:product_detail' product.pk %}" class="btn btn-primary btn-lg btn-block">
                        Купить
                    </a>
                </div>
                <div class="mt-2">
                    <a href="{% url 'catalog:version_detail' product.pk %}" class="btn btn-success btn-lg btn-block">
                        Посмотреть версию
                    </a>
                </div>
                <div class="mt-2">
                    {% if perms.catalog.can_edit_description and perms.catalog.can_edit_category and perms.catalog.can_cancel_publishing or user == product.owner %}
                        <a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-danger btn-lg btn-block">Удалить</a>
                        <a href="{% url 'catalog:product_update' product.pk %}" class="btn btn-warning btn-lg btn-block">Изменить</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data" class="mb-4">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in object_list %}
            {% if product.is_published %}
                <div class="col">
                    <div class="card h-100">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ product.price }}₽</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li><img src="{{ product.photo | media_path }}" width="300" height="225"/></li>
                                <br>
                                <li>
                                    {% if product.description %}
                                        {{ product.description | truncatechars:100 }}
                                    {% else %}
                                        Описание отсутствует.
                                        Ждем, пока продавец его добавит.
                                    {% endif %}
                                </li>
                            </ul>
                            <a href="{% url 'catalog:product_detail' product.pk %}"
                               class="btn btn-lg btn-block btn-outline-primary">Подробнее</a><br>
                        </div>
                    </div>
                </div>
            {% else %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/products.html
{% load static %}
{% load my_tags %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VadimStore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">
</head>
<body>

{% include 'catalog/includes/top.html' %}

<div class="container">
    <div class="row text-center">
        {% for product in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product }}</h4>
                        <img class="card-img-top"
                             src="{{ product.photo | media_path }}"
                             alt="Card image cap">
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ product.price }} ₽</h1>
                        <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            {% if product.description %}
                                {{ product.description | truncatechars:56 }}
                            {% else %}
                                Описание отсутствует.
                                Ждем, пока продавец его добавит.
                            {% endif %}
                        </ul>
                        <a href="#" type="button" class="btn btn-lg btn-block btn-outline-primary">Перейти к товарам</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% include 'catalog/includes/bottom.html' %}

</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/version_detail.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
        </div>
        <div class="row justify-content-center mt-3">
            <div class="col-md-8">
                <div class="text-center">
                    <h2 class="mb-4">Название версии: "{{ object.version_title }}"</h2>
                    <p class="text-muted">Актуальная версия: {{ object.version_number }}</p>
                    <div class="col-md-4 mx-auto mb-4">
                        <a href="{% url 'catalog:version_update' object.pk %}" class="btn btn-warning btn-lg btn-block">Изменить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/version_form.html
{% extends 'catalog/base.html' %}
{% load catalog_tags %}

{% block content %}
    <div class="container mt-5 mb-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" enctype="multipart/form-data" class="mb-4">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                            Сохранить
                        {% else %}
                            Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}